### PR TITLE
Windows Support

### PR DESCRIPTION
**Pull request by mattn**
Currently, windows got buid error. And seems disabling colors on windows.
Below is a patch to enable colors on windows.

### CODE REVIEW

**Comment by dimiro1** [comment]
There is a problem with your PR. If the Stdout is not a terminal the output will include the ANSI escape sequences. You still have to test if the Stdout is a terminal.

```
$ go run example/main.go -banner example/nyancat.txt > hello.txt
```

Thank you.

**Comment by mattn** [comment]
added checking stdout

**Comment by dimiro1** [comment]
You forgot to check on outputANSI function.

``` go
if isColorEnabled && isANSIEnabled() {
    return encodeStart + code + encodeEnd
}
```

**Comment by mattn** [comment]
Ah, sorry. will fix soon.

**Comment by mattn** [comment]
squashed.

**Comment by dimiro1** [comment]
Merged. Thank you.

**Pull request merged**
